"""PPT creator using python-pptx to create professional PPTX files from structured slides.

Each slide: {'heading': str, 'content': str}
"""
import os, uuid, logging
from pptx import Presentation
from pptx.util import Inches, Pt

logger = logging.getLogger('autoscillab.ppt_creator')
OUT_DIR = os.getenv('PPT_OUTPUT_DIR', '/tmp/autoscillab_ppts')
os.makedirs(OUT_DIR, exist_ok=True)

def create_pptx(title: str, slides: list):
    prs = Presentation()
    # Title slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    title_shape = slide.shapes.title
    subtitle = slide.placeholders[1]
    title_shape.text = title
    subtitle.text = 'Auto-generated by AutoSciLab Ultra'

    # Content slides
    for s in slides:
        layout = prs.slide_layouts[1]  # title and content
        sl = prs.slides.add_slide(layout)
        sl.shapes.title.text = s.get('heading', '')[:80]
        body = sl.shapes.placeholders[1].text_frame
        content = s.get('content', '')
        # split into paragraphs
        for i, p in enumerate(content.split('\n')[:8]):
            if i == 0:
                body.text = p
            else:
                p2 = body.add_paragraph()
                p2.text = p
                p2.level = 0
    fname = os.path.join(OUT_DIR, f'{title.replace(" ", "_")}_{uuid.uuid4().hex[:8]}.pptx')
    prs.save(fname)
    logger.info('pptx created: %s', fname)
    return fname
